

# Site settings
title: dogs and bytes // the geeks behind vetrian.com
email: support@vetrian.com
description: > # this means to ignore newlines until "baseurl:"
  dogs and bytes // the geeks behind vetrian.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.vetrian.com" # the base hostname & protocol for your site
permalink: /:title

# Build settings
markdown: kramdown

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
